language: python
dist: xenial
addons:
  apt:
    packages:
    - libpython3.6-dev
python:
    - "3.7-dev"
    - "3.6"
install:
    - pip install -e .
    - pip install codecov
script:
    - python setup.py test
after_success:
    - codecov